name: build

on:
  push:
    branches: [ rust_impl ]
  pull_request:
    branches: [ rust_impl ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libglfw3 libglfw3-dev libxinerama-dev xorg-dev

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build
        run: cargo test; cargo test --examples